# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths:
      - '**/*_brut.md'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**/*_brut.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: Write-Host "Coucou"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          $phrase  = "ca va ?"
          Write-Host $phrase
          
      - name: Get specific changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v25
        with:
          files: |
            **/*_brut.md
            
      - name: List all changed files
        #run: ${{ github.action_path }}/script.ps1 -liste ${{ steps.changed-files-specific.outputs.all_changed_files }}
        run : '& $env:GITHUB_ACTION_PATH/script.ps1 -liste ${{ steps.changed-files-specific.outputs.all_changed_files }}'
        shell: pwsh
          #foreach ($file in ${{ steps.changed-files-specific.outputs.all_changed_files }}){
            #Write-Host "$file was changed"
          #}
